import project1after from "../assets/projects/project-1/IMG_6581.jpeg";
import project1before from "../assets/projects/project-1/IMG_6582.jpeg";

export const projectCategories = [
    { id: "all", label: "Сите проекти" },
    { id: "residential", label: "Станбени објекти" },
    { id: "renovation", label: "Реновирање" },
    { id: "exterior", label: "Надворешно уредување" },
    { id: "paving", label: "Бекатон" },
    { id: "pools", label: "Базени" },
    { id: "finishing", label: "Завршни работи" },
];

export const projects = [
     {
        id: 1,
        slug: "temelna-ploca-za-montazen-objekt",
        title: "Темелна плоча за Монтажен објект",
        category: "residential",
        categoryLabel: "Станбени објекти",
        featured: true,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Изведба на темелна плоча за монтажен станбен објект со целосна подготовка на терен, дренажа и армирано-бетонска конструкција.",
        description:
         "Комплетна изведба на темелна плоча за монтажен станбен објект во Горно Соње. Проектот вклучуваше подготовка и порамнување на теренот, геодетско премерување, ископ и армирање на темели, поставување дренажен систем и изведба на армирано-бетонска конструкција за стабилна и долготрајна основа.",
        location: "Горно Соње, Скопје",
        year: "2026",
        type: "Станбен објект",
        area: "80 m²",
        duration: "1 месец",
        workPerformed: [
            "Порамнување и подготовка на терен",
            "Геодетско премерување",
            "Ископ и армирање на темели",
            "Поставување дренажни цевки",
            "Изведба на темелна плоча",
        ],
        images: [project1after],
    },
    {
        id: 2,
        slug: "renoviranje-kuka-skopje",
        title: "Целосно реновирање на куќа",
        category: "renovation",
        categoryLabel: "Реновирање",
        featured: true,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Комплетно реновирање и реконструкција на станбен објект со структурни измени, нов кров, фасада и уредување на надворешен простор.",
        description: "Целосна реконструкција на постоечки станбен објект во Кисела Вода со адаптација на просториите, нова инфраструктура и современи градежни решенија. Проектот опфати конструктивни промени, замена на кров, фасада, нови инсталации и целосно уредување на дворното место.",
        location: "Кисела Вода, Скопје",
        year: "2026",
        type: "Реновирање",
        area: "60 m²",
        duration: "2 месеци",
        workPerformed: [
            "Рушење и адаптација на простории",
            "Изведба на нов кров",
            "Монтажа на нова дограма",
            "Нови водоводни и одводни инсталации",
            "Реновирање на кујна и купатило",
            "Изведба на фасада",
            "Ограда и влезна капија"
        ],
        images: [project1after],
    },
    {
        id: 3,
        slug: "vikend-kuka",
        title: "Реконструкција и доградба на викендица",
        category: "residential",
        categoryLabel: "Станбени објекти",
        featured: true,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Целосно реновирање на веќепостоечки објект, и доградба на спрат и кров.",
        description: "Комплетно реновирање и доградба на постоечки викенд објект во с. Мирковци. Проектот опфати структурно проширување со нов спрат, кровна конструкција, фасада, внатрешно уредување и уредување на надворешниот простор.",
        location: "с.Мирковци, Скопје",
        year: "2025",
        type: "Викендица",
        area: "50 m²",
        duration: "4 месеци",
        workPerformed: [
            "Реновирање на постоечки објект",
            "Доградба на нов спрат",
            "Изведба на плоча и конструкција",
            "Кровна конструкција",
            "Водоводна и одводна мрежа",
            "Гипс картон и внатрешно уредување",
            "Уредување на двор"
        ],
        images: [
            project1before,
            project1after        
        ],
    },
    {
        id: 4,
        slug: "adaptacija-deloven-prostor",
        title: "Адаптација на деловен простор",
        category: "renovation",
        categoryLabel: "Реновирање",
        featured: false,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Преуредување на деловен простор со фокус на функционалност, професионален изглед и практична употреба.",
        description: "Проект за адаптација на постоечки простор во современа деловна средина со квалитетни завршни работи.",
        location: "Куманово",
        year: "2024",
        type: "Деловен простор",
        area: "140 m²",
        duration: "2 месеци",
        images: [project1before],
    },
    {
        id: 5,
        slug: "dvorno-ureduvanje-ohrid",
        title: "Уредување на двор",
        category: "exterior",
        categoryLabel: "Надворешно уредување",
        featured: true,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Уредување на двор со патеки, зелени површини, потпорни елементи и практично организиран надворешен простор.",
        description: "Изведба на надворешен простор со комбинација од функционалност, естетика и квалитетни материјали.",
        location: "Охрид",
        year: "2024",
        type: "Надворешно уредување",
        area: "250 m²",
        duration: "5 недели",
        images: [project1after],
    },
    {
        id: 6,
        slug: "potporen-zid-i-skali",
        title: "Потпорен ѕид и надворешни скали",
        category: "exterior",
        categoryLabel: "Надворешно уредување",
        featured: false,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Изградба на потпорен ѕид и скали за стабилен, безбеден и функционален пристап до дворното место.",
        description: "Проект со фокус на стабилност на терен, сигурна изведба и практично користење на надворешниот простор.",
        location: "Тетово",
        year: "2023",
        type: "Потпорен ѕид",
        area: "90 m²",
        duration: "4 недели",
        images: [project1before],
    },
    {
        id: 7,
        slug: "bekaton-dvor-skopje",
        title: "Бекатон во двор",
        category: "paving",
        categoryLabel: "Бекатон и поплочување",
        featured: false,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Поставување бекатон во двор со прецизна подготовка, правилен пад и чиста завршна линија.",
        description: "Изведба на бекатонска површина со квалитетна подлога, стабилност и долгорочна издржливост.",
        location: "Скопје",
        year: "2025",
        type: "Бекатон",
        area: "160 m²",
        duration: "2 недели",
        images: [project1after],
    },
    {
        id: 8,
        slug: "parking-prostor-bekaton",
        title: "Паркинг простор со бекатон",
        category: "paving",
        categoryLabel: "Бекатон и поплочување",
        featured: false,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Изведба на практичен паркинг простор со бекатон, стабилна подлога и правилно одводнување.",
        description: "Проект за поплочување на паркинг површина со издржливи материјали и функционално решение за секојдневна употреба.",
        location: "Велес",
        year: "2024",
        type: "Поплочување",
        area: "220 m²",
        duration: "3 недели",
        images: [project1before],
    },
    {
        id: 9,
        slug: "bazen-vo-dvor",
        title: "Базен во двор",
        category: "pools",
        categoryLabel: "Базени",
        featured: false,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Изградба на дворен базен со квалитетна конструкција, чиста завршна обработка и функционален простор околу него.",
        description: "Проект за базен со фокус на стабилна изведба, практична околина и естетски вклопен надворешен простор.",
        location: "Скопје",
        year: "2025",
        type: "Базен",
        area: "45 m²",
        duration: "2 месеци",
        images: [project1after],
    },
    {
        id: 10,
        slug: "zavrsni-raboti-kuka",
        title: "Завршни работи во куќа",
        category: "finishing",
        categoryLabel: "Завршни работи",
        featured: false,
        beforeImg: project1before,
        afterImg: project1after,
        shortDescription: "Изведба на плочки, гипс-картон, молерисување и декоративни детали за комплетен ентериер.",
        description: "Завршна обработка на станбен простор со професионален пристап и внимание на деталите.",
        location: "Битола",
        year: "2024",
        type: "Завршни работи",
        area: "150 m²",
        duration: "5 недели",
        images: [project1before],
    },
   
];