import project1after from "../assets/projects/project-1/IMG_6581.jpeg";
import project1before from "../assets/projects/project-1/IMG_6582.jpeg";

export const projectCategories = [
    { id: "all", label: "Сите проекти" },
    { id: "residential", label: "Станбени објекти" },
    { id: "renovation", label: "Реновирање" },
    { id: "exterior", label: "Надворешно уредување" },
    { id: "paving", label: "Бекатон" },
    { id: "pools", label: "Базени" },
    { id: "finishing", label: "Завршни работи" },
];

export const projects = [
    {
        id: 1,
        slug: "stanbena-kuka-skopje",
        title: "Станбена куќа во Скопје",
        category: "residential",
        categoryLabel: "Станбени објекти",
        featured: true,
        coverImage: project1after,
        shortDescription: "Изградба на семејна куќа со современ пристап, стабилна конструкција и квалитетна завршна изведба.",
        description: "Комплетна изведба на станбен објект со внимание на конструкција, функционалност, енергетска ефикасност и долгорочен квалитет.",
        location: "Скопје",
        year: "2025",
        type: "Станбен објект",
        area: "180 m²",
        duration: "4 месеци",
        images: [project1after],
    },
    {
        id: 2,
        slug: "vikendica-vo-planina",
        title: "Викендица во планински предел",
        category: "residential",
        categoryLabel: "Станбени објекти",
        featured: true,
        coverImage: project1before,
        shortDescription: "Изведба на викендица со практичен распоред, цврста конструкција и природно вклопување во околината.",
        description: "Проект со фокус на удобност, издржливост и топол семеен простор погоден за одмор и долгорочно користење.",
        location: "Маврово",
        year: "2024",
        type: "Викендица",
        area: "120 m²",
        duration: "3 месеци",
        images: [project1before],
    },
    {
        id: 3,
        slug: "renoviranje-stan-skopje",
        title: "Целосно реновирање на стан",
        category: "renovation",
        categoryLabel: "Реновирање",
        featured: true,
        coverImage: project1after,
        shortDescription: "Комплетна адаптација на станбен простор со модерна организација, нови материјали и чиста завршна обработка.",
        description: "Реновирање на стан со демонтажа, подготовка, завршни работи и подобрување на функционалноста на просторот.",
        location: "Скопје",
        year: "2025",
        type: "Реновирање",
        area: "85 m²",
        duration: "6 недели",
        images: [project1after],
    },
    {
        id: 4,
        slug: "adaptacija-deloven-prostor",
        title: "Адаптација на деловен простор",
        category: "renovation",
        categoryLabel: "Реновирање",
        featured: false,
        coverImage: project1before,
        shortDescription: "Преуредување на деловен простор со фокус на функционалност, професионален изглед и практична употреба.",
        description: "Проект за адаптација на постоечки простор во современа деловна средина со квалитетни завршни работи.",
        location: "Куманово",
        year: "2024",
        type: "Деловен простор",
        area: "140 m²",
        duration: "2 месеци",
        images: [project1before],
    },
    {
        id: 5,
        slug: "dvorno-ureduvanje-ohrid",
        title: "Уредување на двор",
        category: "exterior",
        categoryLabel: "Надворешно уредување",
        featured: true,
        coverImage: project1after,
        shortDescription: "Уредување на двор со патеки, зелени површини, потпорни елементи и практично организиран надворешен простор.",
        description: "Изведба на надворешен простор со комбинација од функционалност, естетика и квалитетни материјали.",
        location: "Охрид",
        year: "2024",
        type: "Надворешно уредување",
        area: "250 m²",
        duration: "5 недели",
        images: [project1after],
    },
    {
        id: 6,
        slug: "potporen-zid-i-skali",
        title: "Потпорен ѕид и надворешни скали",
        category: "exterior",
        categoryLabel: "Надворешно уредување",
        featured: false,
        coverImage: project1before,
        shortDescription: "Изградба на потпорен ѕид и скали за стабилен, безбеден и функционален пристап до дворното место.",
        description: "Проект со фокус на стабилност на терен, сигурна изведба и практично користење на надворешниот простор.",
        location: "Тетово",
        year: "2023",
        type: "Потпорен ѕид",
        area: "90 m²",
        duration: "4 недели",
        images: [project1before],
    },
    {
        id: 7,
        slug: "bekaton-dvor-skopje",
        title: "Бекатон во двор",
        category: "paving",
        categoryLabel: "Бекатон и поплочување",
        featured: true,
        coverImage: project1after,
        shortDescription: "Поставување бекатон во двор со прецизна подготовка, правилен пад и чиста завршна линија.",
        description: "Изведба на бекатонска површина со квалитетна подлога, стабилност и долгорочна издржливост.",
        location: "Скопје",
        year: "2025",
        type: "Бекатон",
        area: "160 m²",
        duration: "2 недели",
        images: [project1after],
    },
    {
        id: 8,
        slug: "parking-prostor-bekaton",
        title: "Паркинг простор со бекатон",
        category: "paving",
        categoryLabel: "Бекатон и поплочување",
        featured: false,
        coverImage: project1before,
        shortDescription: "Изведба на практичен паркинг простор со бекатон, стабилна подлога и правилно одводнување.",
        description: "Проект за поплочување на паркинг површина со издржливи материјали и функционално решение за секојдневна употреба.",
        location: "Велес",
        year: "2024",
        type: "Поплочување",
        area: "220 m²",
        duration: "3 недели",
        images: [project1before],
    },
    {
        id: 9,
        slug: "bazen-vo-dvor",
        title: "Базен во двор",
        category: "pools",
        categoryLabel: "Базени",
        featured: true,
        coverImage: project1after,
        shortDescription: "Изградба на дворен базен со квалитетна конструкција, чиста завршна обработка и функционален простор околу него.",
        description: "Проект за базен со фокус на стабилна изведба, практична околина и естетски вклопен надворешен простор.",
        location: "Скопје",
        year: "2025",
        type: "Базен",
        area: "45 m²",
        duration: "2 месеци",
        images: [project1after],
    },
    {
        id: 10,
        slug: "zavrsni-raboti-kuka",
        title: "Завршни работи во куќа",
        category: "finishing",
        categoryLabel: "Завршни работи",
        featured: false,
        coverImage: project1before,
        shortDescription: "Изведба на плочки, гипс-картон, молерисување и декоративни детали за комплетен ентериер.",
        description: "Завршна обработка на станбен простор со професионален пристап и внимание на деталите.",
        location: "Битола",
        year: "2024",
        type: "Завршни работи",
        area: "150 m²",
        duration: "5 недели",
        images: [project1before],
    },
];

export const featuredProjects = [
  {
    id: 1,
    title: "Реновирање на викенд куќа",
    category: "Реновирање и адаптација",
    location: "с. Мирковци, Скопје",
    description:
      "Целосна реконструкција и модернизација на станбен објект. Додавање на спрат, реконструкција на кров, изработка на фасада и уредување на двор.",
    beforeImg: project1before,
    afterImg: project1after,
  },
  {
    id: 2,
    title: "Изградба на семејна куќа",
    category: "Станбени објекти",
    location: "Охрид",
    description:
      "Изградба на современа семејна куќа со комплетна надворешна фасада, двор и завршни градежни работи.",
    beforeImg: "https://images.unsplash.com/photo-1587582423116-ec07293f0395?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    afterImg: project1after,
  },
  {
    id: 3,
    title: "Уредување на деловен простор",
    category: "Деловни објекти",
    location: "Скопје",
    description:
      "Адаптација и уредување на деловен простор со нови подови, осветлување и модерни ентериерни решенија.",
    beforeImg: project1before,
    afterImg: project1after,
  },
  {
    id: 4,
    title: "Уредување на двор и базен",
    category: "Надворешно уредување",
    location: "Тетово",
    description:
      "Поставување бекатон, изградба на потпорни ѕидови и комплетно уредување на дворен простор со базен.",
    beforeImg: project1before,
    afterImg: project1after,
  },
];