import { project1Images } from "./projectImages/project1Images";
import { project2Images } from "./projectImages/project2Images";
import { project3Images } from "./projectImages/project3Images";
import { project4Images } from "./projectImages/project4Images";
import { project5Images } from "./projectImages/project5Images";

export const projectCategories = [
    { id: "all", label: "Сите проекти" },
    { id: "residential", label: "Станбени објекти" },
    { id: "renovation", label: "Реновирање" },
    { id: "exterior", label: "Надворешно уредување" },
    { id: "paving", label: "Бекатон" },
    { id: "pools", label: "Базени" },
    { id: "finishing", label: "Завршни работи" },
];

export const projects = [
     {
        id: 1,
        slug: "temelna-ploca-za-montazen-objekt",
        title: "Темелна плоча за Монтажен објект",
        category: "residential",
        categoryLabel: "Станбени објекти",
        featured: true,
        beforeImg: project1Images.before,
        afterImg: project1Images.after,
        shortDescription: "Изведба на темелна плоча за монтажен станбен објект со целосна подготовка на терен, дренажа и армирано-бетонска конструкција.",
        description:
         "Комплетна изведба на темелна плоча за монтажен станбен објект во Горно Соње. Проектот вклучуваше подготовка и порамнување на теренот, геодетско премерување, ископ и армирање на темели, поставување дренажен систем и изведба на армирано-бетонска конструкција за стабилна и долготрајна основа.",
        location: "Горно Соње, Скопје",
        year: "2026",
        type: "Станбен објект",
        area: "80 m²",
        duration: "1 месец",
        workPerformed: [
            "Порамнување и подготовка на терен",
            "Геодетско премерување",
            "Ископ и армирање на темели",
            "Поставување дренажни цевки",
            "Изведба на темелна плоча",
        ],
        images: project1Images.gallery,
    },
    {
        id: 2,
        slug: "renoviranje-kuka-skopje",
        title: "Целосно реновирање на куќа",
        category: "renovation",
        categoryLabel: "Реновирање",
        featured: true,
        beforeImg: project2Images.before,
        afterImg: project2Images.after,
        shortDescription: "Комплетно реновирање и реконструкција на станбен објект со структурни измени, нов кров, фасада и уредување на надворешен простор.",
        description: "Целосна реконструкција на постоечки станбен објект во Кисела Вода со адаптација на просториите, нова инфраструктура и современи градежни решенија. Проектот опфати конструктивни промени, замена на кров, фасада, нови инсталации и целосно уредување на дворното место.",
        location: "Кисела Вода, Скопје",
        year: "2026",
        type: "Реновирање",
        area: "60 m²",
        duration: "2 месеци",
        workPerformed: [
            "Рушење и адаптација на простории",
            "Изведба на нов кров",
            "Монтажа на нова дограма",
            "Нови водоводни и одводни инсталации",
            "Реновирање на кујна и купатило",
            "Изведба на фасада",
            "Ограда и влезна капија"
        ],
         images: project2Images.gallery,
    },
    {
        id: 3,
        slug: "vikend-kuka",
        title: "Реконструкција и доградба на викендица",
        category: "residential",
        categoryLabel: "Станбени објекти",
        featured: true,
        beforeImg: project3Images.before,
        afterImg: project3Images.after,
        shortDescription: "Целосно реновирање на веќепостоечки објект, и доградба на спрат и кров.",
        description: "Комплетно реновирање и доградба на постоечки викенд објект во с. Мирковци. Проектот опфати структурно проширување со нов спрат, кровна конструкција, фасада, внатрешно уредување и уредување на надворешниот простор.",
        location: "с.Мирковци, Скопје",
        year: "2025",
        type: "Викендица",
        area: "50 m²",
        duration: "4 месеци",
        workPerformed: [
            "Реновирање на постоечки објект",
            "Доградба на нов спрат",
            "Изведба на плоча и конструкција",
            "Кровна конструкција",
            "Водоводна и одводна мрежа",
            "Гипс картон и внатрешно уредување",
            "Уредување на двор"
        ],
         images: project3Images.gallery,
    },
    {
        id: 4,
        slug: "renoviranje-krov-nerezi",
        title: "Целосно реновирање на кров",
        category: "renovation",
        categoryLabel: "Реновирање",
        featured: true,
        beforeImg: project4Images.before,
        afterImg: project4Images.after,
        shortDescription:
            "Комплетна реконструкција на кровна конструкција со замена на оштетени елементи и поставување нов покривен систем.",

        description:
            "Проектот опфати целосно реновирање на постоечки кров на станбен објект со цел подобрување на стабилноста и долготрајноста на конструкцијата. Извршена е демонтажа на стариот кров, замена на оштетените дрвени елементи и изработка на нова кровна конструкција. По завршување на конструктивните работи поставен е нов покрив со квалитетна изведба и внимание на секој детал.",
        location: "Скопје",
        year: "2026",
        type: "Реновирање на кров",
        area: "180 m²",
        duration: "1 недела",
        workPerformed: [
            "Демонтажа на постоечки кров",
            "Отстранување на оштетени елементи",
            "Изработка на нова дрвена конструкција",
            "Зајакнување на носечките делови",
            "Поставување на нов покрив",
            "Завршни градежни работи",
        ],
         images: project4Images.gallery,
    },
    {
        id: 5,
        slug: "postavuvanje-bekaton-ilinden",
        title: "Поставување на бекатон во двор",
        category: "exterior",
        categoryLabel: "Надворешно уредување",
        featured: false,       
        beforeImg: project5Images.before,
        afterImg: project5Images.after,
        shortDescription:
            "Уредување на дворен простор со поставување на бекатон, подготовка на подлога и изведба на функционални пешачки и пристапни површини.",

        description:
            "Проектот опфати целосно уредување на дворен простор во Илинден со поставување на бекатон на претходно подготвена подлога. Извршено е расчистување и порамнување на теренот, подготовка на подлогата и прецизно поставување на бекатон со цел добивање на функционален, издржлив и визуелно уреден надворешен простор. Посебно внимание беше посветено на нивелацијата и завршната обработка за да се обезбеди долготрајност и квалитет на изведбата.",

        location: "Илинден, Скопје",
        year: "2025",
        type: "Поставување на бекатон",
        area: "200 m²",
        duration: "2 недели",

        workPerformed: [
            "Расчистување и подготовка на терен",
            "Порамнување на подлогата",
            "Тампонирање на површината",
            "Поставување на рабници",
            "Поставување на бекатон",
            "Нивелирање и завршна обработка",
            "Уредување на пристапни и пешачки површини"
        ],
        images: project5Images.gallery,
        },
    {
        id: 6,
        slug: "izgradba-letnikovec-manastir",
        title: "Изградба на летниковец на Манастирот 'Св.Петар и Павле'",
        category: "exterior",
        categoryLabel: "Надворешно уредување",
        featured: false,
        beforeImg: project3Images.before,
        afterImg: project3Images.after,
        shortDescription: "Изградба на потпорен ѕид и скали за стабилен, безбеден и функционален пристап до дворното место.",
        description: "Изградба на голем летниковец во Манастирскиот двор. Изработка на мали кровчиња на помошните влезови во Манастирот, изработка на дрвена ограда покрај бекатонската патека, околу Манастирот. Изработка на крововите на камбанаријата на Манастирот.",
        location: "с.Ајватовци, Скопје",
        year: "2024",
        type: "Летниковец",
        area: "200 m²",
        duration: "6 недели",
        images: project5Images.gallery,
    },
    {
        id: 7,
        slug: "fasada-bardovci",
        title: "Изработка на фасада на семејна куќа",
        category: "finishing",
        categoryLabel: "Завршни работи",
        featured: false,
        beforeImg: project3Images.before,
        afterImg: project3Images.after,
        shortDescription: "Изработка на фасада од стиропор на семејна куќа во населба Бардовци",
        description: "Изработка на фасада со стиропор комбинирано(10цм, 5цм и 3цм) на целосна куќа. Припрема на внатрешни ѕидови од купатило и кујни,(влечење на лепак, мрежа и порамнување на ѕидови).Изнесување на отпаден материјал (шут).",
        location: "Бардовци, Скопје",
        year: "2025",
        type: "Завршмни работи",
        area: "400 m²",
        duration: "3 месеци",
         images: project5Images.gallery,
    },
    {
        id: 8,
        slug: "renoviranje-krov-voddno",
        title: "Реновирање на кров на семејна куќа",
        category: "renovation",
        categoryLabel: "Реновирање на кров",
        featured: false,
        beforeImg: project3Images.before,
        afterImg: project3Images.after,
        shortDescription: "Комплетна реконструкција на кровна конструкција со замена на оштетени елементи и поставување нов покривен систем.",
        description: "Демонтажа на стари керамиди, стари летви. Монтирање на нова паропропусна фолија, два пара летви и поставување на нови керамиди (тондак). И поставување на капаци на кровот. Изнесување на отпаден материјал(шут).",
        location: "населба Водно, Скопје",
        year: "2026",
        type: "Реновирање",
        area: "80 m²",
        duration: "1 недела",
         images: project5Images.gallery,
    },
    {
        id: 9,
        slug: "bazen-vo-dvor",
        title: "Базен во двор",
        category: "pools",
        categoryLabel: "Базени",
        featured: false,
         beforeImg: project3Images.before,
        afterImg: project3Images.after,
        shortDescription: "Изградба на дворен базен со квалитетна конструкција, чиста завршна обработка и функционален простор околу него.",
        description: "Проект за базен со фокус на стабилна изведба, практична околина и естетски вклопен надворешен простор.",
        location: "Скопје",
        year: "2025",
        type: "Базен",
        area: "45 m²",
        duration: "2 месеци",
        images: project5Images.gallery
    },
    {
        id: 10,
        slug: "zavrsni-raboti-kuka",
        title: "Завршни работи во куќа",
        category: "finishing",
        categoryLabel: "Завршни работи",
        featured: false,
         beforeImg: project3Images.before,
        afterImg: project3Images.after,
        shortDescription: "Изведба на плочки, гипс-картон, молерисување и декоративни детали за комплетен ентериер.",
        description: "Завршна обработка на станбен простор со професионален пристап и внимание на деталите.",
        location: "Битола",
        year: "2024",
        type: "Завршни работи",
        area: "150 m²",
        duration: "5 недели",
        images: project5Images.gallery,
    },
   
];